name: 每日签到任务

on:
  # 触发条件：定时 + 代码推送 + 手动
  schedule:
    - cron: 45 15 * * *'  # UTC 0点（北京时间8点）
  push:                   # 添加代码推送触发
    branches: [ main ]
  workflow_dispatch:

jobs:
  sign_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载最新代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    - name: 清除缓存
      run: pip cache purge  # 清除旧缓存
    
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: 安装依赖
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 执行签到脚本
      run: python "自动签到-无法弄弄.py"  # 确保文件名正确
